cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kubectx'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'shpotify'
brew 'spaceman-diff'
brew 'spark'
brew 'speedtest-cli'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'